### ISSUE TITLE
Required root in alias throwing error in local environment

### ISSUE THREAD

**Issue by shelane** [consolidation/site-alias#18] opened 2018-11-01 21:30 UTC
### Steps to reproduce
Running Drupal install with Acquia BLT
`blt drupal:install`

### Expected behavior
Drupal should install

### Actual behavior
```
In AliasRecord.php line 76:
                                                      
  [Exception]                                         
  Site alias @default.local does not specify a root.  
```

### System Configuration
Which O.S. and PHP version are you using?
This is in a Docker environment (Docksal specifically) with PHP 7.1 and Acquia BLT installed.

Local drush file looks like:
```
options:
  uri: 'http://d8t.docksal'
```

I tried adding root as such and still get the error:
```
options:
  uri: 'http://d8t.docksal'
  root: '/var/www/docroot/sites/default'
```
This occurred after I updated from 1.1.5 to 1.1.9 today.

**Comment by greg-1-anderson** [comment] 2018-11-01 21:40
This started with https://github.com/consolidation/site-alias/pull/11/commits/c44fb4b5b5e91437e2e1a9d63d8f6dee7648e9b6, and ended with #11 throwing an exception when the root element is empty.

The issue is that `$alias->root()` was ambiguous when called without a defined root. Per the intended API, clients were supposed to call `hasRoot()` first if the root is not guaranteed to exist. The method `root()` was returning indeterminate results under those conditions. I therefore made this change as a bug fix / API clarification, even though it has the potential to break (non-conformant) clients.

So, this will need to be fixed in blt, with my apologies. You can pin to 1.1.5 until this is done. If this is a large enough problem, I would consider rolling back this change in the 1.x branch, and make a 2.x branch with the fix.

**Comment by shelane** [comment] 2018-11-01 21:42
I will pin to 1.1.5 for now and report the issue to Acquia for BLT.

**Comment by shelane** [comment] 2018-11-01 21:48
Can you point to documentation on how the alias file should be formatted? As I mentioned above, my inclusion of "root" still resulted in the same error.

**Comment by greg-1-anderson** [comment] 2018-11-01 23:49
Rolled back the breaking change in site-alias 1.1.10.

Apps that use the site-alias project should update to the ^2 version as soon as convenient.

**Closed by greg-1-anderson** 2018-11-01 23:49 UTC
