### ISSUE TITLE
Uncaught Error: Class "Symfony\Component\Filesystem\Path" not found

### ISSUE THREAD

**Issue by ThomWilhelm** [consolidation/site-alias#56] opened 2022-10-11 22:58 UTC
### Steps to reproduce
When installing 3.1.6 I get errors when trying to using drush sql-sync.

### Expected behavior
The action completes with no errors.

### Actual behavior
I get the following error:

```
  Error Output:                                                                                                                                                                                           
  ================                                                                                                                                                                                        
  PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Filesystem\Path" not found in /var/www/drupalvm/vendor/consolidation/site-alias/src/HostPath.php:156                                         
  Stack trace:
```

This is because symfony/filesystem 4.4 doesn't have Path.php, this only exists in 5.x and above:
https://github.com/symfony/filesystem/tree/4.4

I also can't upgrade to symfony/filesystem 5.0 or newer because I believe core has locked this to ^4.4:

```
vagrant@rfep:/var/www/drupalvm/docroot$ composer require symfony/filesystem:^5.0
No composer.json in current directory, do you want to use the one at /var/www/drupalvm? [Y,n]? 
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update symfony/filesystem
Gathering patches for root package.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/core-dev is locked to version 9.4.8 and an update of this package was not requested.
    - drupal/core-dev 9.4.8 requires symfony/filesystem ^4.4 -> found symfony/filesystem[v4.4.0-BETA1, ..., 4.4.x-dev] but it conflicts with your root composer.json require (^5.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

For now I'll just roll back to the 3.1.5 release.

**Comment by MdNadimHossain** [comment] 2022-10-13 09:57
ah I just created an issue exactly because of this same problem. I think this change should be reverted - https://github.com/consolidation/site-alias/compare/3.1.5...3.1.6#diff-0a314e29b8c6ad95b51c5b8c969384c05fbf40875a8253e7b23bf1d5a4ec0fdfL6
Until the path gets added to `symfony/filesystem 4.x`

**Comment by greg-1-anderson** [comment] 2022-10-15 01:25
Duplicate of #57

**Closed by greg-1-anderson** 2022-10-15 01:25 UTC
